# Generated by Django 3.2.13 on 2022-05-08 02:19

import consumer.models.consumer
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('collected', 'collected'), ('In_progress', 'In_progress'), ('active', 'active')], default=consumer.models.consumer.ConsumerStatusType['active'], max_length=16)),
                ('previous_jobs_count', models.PositiveBigIntegerField()),
                ('amount_due', models.IntegerField(default=0)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
